### ISSUE TITLE
support the RADIUS Challenge-Response mode

### ISSUE THREAD

**Issue by likaozheng** [ValdikSS/openvpn-radiusplugin#13]
Hi!
I am using this plugin recently. It's very helpful.
I konw it does not support the RADIUS Challenge-Response. If the radius server denied the access or sends a ACCESS_CHALLENGE-packet, it raise an error.
But currently openvpn already supports the RADIUS Challenge-Response mode.
So are you plainning to  release it to support Challenge-Response mode?
Thanks!

https://openvpn.net/index.php/open-source/documentation/miscellaneous/79-management-interface.html
the section 'Challenge/Response Protocol'

**Comment by ValdikSS** [comment]
I'm not interested in supporting this plugin anymore. Take a look at it's forks: https://github.com/ValdikSS/openvpn-radiusplugin/network

**Comment by likaozheng** [comment]
Thanks!

**Comment by josephholsten** [comment]
@ValdikSS you may want to archive the repo by: https://help.github.com/articles/archiving-repositories/
