### ISSUE TITLE
How to set status and client-config-dir in radiusplugin.cnf

### ISSUE THREAD

**Issue by dawei1** [ValdikSS/openvpn-radiusplugin#3]
I tried to point status to the actual status file generated by openvpn so that I can have traffic statistics of connected client but it seems the plugin just ignore it and nothing regarding traffic shows up in the radius database (login auth and other accounting info are OK). The same thing happens to the client-config-dir also, the actual client config file always appears in /etc/openvpn. Would you please show me how to properly set these two variable in radiusplugin.cnf? Thank you.

**Comment by ValdikSS** [comment]
You need to write full path in case you're writing relative. Radiusplugin supports only status files version 1 in case you changed it in OpenVPN configuration.

**Comment by dawei1** [comment]
Thanks for the promptly reply. Yes I am using full path e.g. :
status /etc/openvpn/server-status.log

And the version is set explicitly to 1. Is there any log from the plugin?

**Comment by ValdikSS** [comment]
Yes, you should be able to see plugin output in stdout/stderr. It can't write into logfile.

**Comment by ValdikSS** [comment]
Did you solve your problem?

**Comment by dawei1** [comment]
Thanks for following up. Yes I solved the problem. I explicitly set the log version to 1, change the permission of the log file. Now the accounting function is working perfectly.
