### ISSUE TITLE
Errors in openvpn log

### ISSUE THREAD

**Issue by deba12** [ValdikSS/openvpn-radiusplugin#4]
Hello,
i have an errors in openvpn.log:
Sat Nov  5 11:34:15 2016 RADIUS-PLUGIN: BACKGROUND-ACCT:  Fail to add attribute ATTRIB_User_Password.
No value in the Attribute!
Sat Nov  5 11:35:15 2016 RADIUS-PLUGIN: BACKGROUND-ACCT:  Fail to add attribute ATTRIB_User_Password.
No value in the Attribute!
Sat Nov  5 11:36:15 2016 RADIUS-PLUGIN: BACKGROUND-ACCT:  Fail to add attribute ATTRIB_User_Password.
No value in the Attribute!
Sat Nov  5 11:37:15 2016 RADIUS-PLUGIN: BACKGROUND-ACCT:  Fail to add attribute ATTRIB_User_Password.
No value in the Attribute!
Sat Nov  5 11:38:15 2016 RADIUS-PLUGIN: BACKGROUND-ACCT:  Fail to add attribute ATTRIB_User_Password.
No value in the Attribute!

i think that errors are some how related to interim accounting update 
what can i do ?

thanks,

**Comment by ValdikSS** [comment]
Do you use username/password authentication?

**Comment by deba12** [comment]
yes

**Comment by ValdikSS** [comment]
I'll check it.

**Comment by deba12** [comment]
Do you need to provide you with radius.conf and openvpn.conf?

**Comment by ValdikSS** [comment]
Yes please, this would be helpful. Please send files to iam@valdikss.org.ru

**Comment by deba12** [comment]
@ValdikSS do you need something more ?

**Comment by deba12** [comment]
bump! :)
